{{- if .Values.daemonset.enabled }}
{{- if (or (.Values.datadog.apiKeyExistingSecret) (.Values.datadog.apiKey)) }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "datadog.fullname" . }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: "{{ template "datadog.fullname" . }}"
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "datadog.fullname" . }}
        {{- if .Values.daemonset.podLabels }}
{{ toYaml .Values.daemonset.podLabels | indent 6 }}
        {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "datadog.fullname" . }}
        {{- if .Values.daemonset.podLabels }}
{{ toYaml .Values.daemonset.podLabels | indent 8 }}
        {{- end }}
      name: {{ template "datadog.fullname" . }}
      annotations:
        checksum/autoconf-config: {{ tpl (toYaml .Values.datadog.autoconf) . | sha256sum }}
        checksum/confd-config: {{ tpl (toYaml .Values.datadog.confd) . | sha256sum }}
        checksum/checksd-config: {{ tpl (toYaml .Values.datadog.checksd) . | sha256sum }}
        {{- if .Values.daemonset.customAgentConfig }}
        checksum/agent-config: {{ tpl (toYaml .Values.daemonset.customAgentConfig) . | sha256sum }}
        {{- end }}
        {{- if and .Values.datadog.systemProbe.enabled }}
        container.apparmor.security.beta.kubernetes.io/system-probe: {{ .Values.datadog.systemProbe.apparmor }}
        container.seccomp.security.alpha.kubernetes.io/system-probe: {{ .Values.datadog.systemProbe.seccomp }}
        {{- end }}
      {{- if .Values.daemonset.podAnnotations }}
{{ toYaml .Values.daemonset.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.datadog.securityContext }}
      securityContext:
{{ toYaml .Values.datadog.securityContext | indent 8 }}
      {{- end }}
      {{- if .Values.daemonset.useHostNetwork }}
      hostNetwork: {{ .Values.daemonset.useHostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      {{- if .Values.daemonset.useHostPID }}
      hostPID: {{ .Values.daemonset.useHostPID }}
      {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.pullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.daemonset.priorityClassName }}
      priorityClassName: {{ .Values.daemonset.priorityClassName }}
      {{- end }}
      containers:
        {{- include "container-agent" . | nindent 8 }}
        {{- if .Values.datadog.apm.enabled }}
          {{- include "container-trace-agent" . | nindent 8 }}
        {{- end }}
        {{- if or (kindIs "invalid" .Values.datadog.processAgent.enabled) .Values.datadog.processAgent.enabled }}
          {{- include "container-process-agent" . | nindent 8 }}
        {{- end }}
        {{- if .Values.datadog.systemProbe.enabled }}
          {{- include "container-system-probe" . | nindent 8 }}
        {{- end }}
      initContainers:
        {{ include "containers-init" . | nindent 8 }}
        {{- if and .Values.datadog.systemProbe.enabled (eq .Values.datadog.systemProbe.seccomp "localhost/system-probe") }}
          {{ include "system-probe-init" . | nindent 8 }}
        {{- end }}
      volumes:
        - name: config
          emptyDir: {}
        {{- if .Values.datadog.criSocketPath }}
        - hostPath:
            path: {{ .Values.datadog.criSocketPath }}
          name: runtimesocket
        {{- end }}
        {{- if .Values.datadog.useDogStatsDSocketVolume }}
        - hostPath:
            path: "/var/run/datadog/"
          name: dsdsocket
        {{- end }}
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - name: s6-run
          emptyDir: {}
        {{- if (or (.Values.datadog.confd) (.Values.datadog.autoconf)) }}
        - name: confd
          configMap:
            name: {{ template "datadog.fullname" . }}-confd
        {{- end }}
        {{- if .Values.datadog.checksd }}
        - name: checksd
          configMap:
            name: {{ template "datadog.fullname" . }}-checksd
        {{- end }}
        {{- if .Values.datadog.logsEnabled }}
        - hostPath:
            path: {{ default "/var/lib/datadog-agent/logs" .Values.datadog.logsPointerHostPath | quote }}
          name: pointerdir
        - hostPath:
            path: /var/log/pods
          name: logpodpath
        {{- if regexFind "^.*docker.*$" $.Values.datadog.criSocketPath }}
        - hostPath:
            path: /var/lib/docker/containers
          name: logdockercontainerpath
        {{- end }}
        {{- end }}
        {{- if or .Values.datadog.processAgent.enabled .Values.datadog.systemProbe.enabled }}
        - hostPath:
            path: /etc/passwd
          name: passwd
        {{- end }}
        {{- if and .Values.datadog.systemProbe.enabled }}
        - name: sysprobe-config
          configMap:
            name: {{ template "datadog.fullname" . }}-system-probe-config
        {{- if eq .Values.systemProbe.seccomp "localhost/system-probe" }}
        - name: datadog-agent-security
          configMap:
            name: {{ template "datadog.fullname" . }}-security
        - hostPath:
            path: {{ .Values.datadog.systemProbe.seccompRoot }}
          name: seccomp-root
        {{- end }}
        - hostPath:
            path: /sys/kernel/debug
          name: debugfs
        - name: sysprobe-socket-dir
          emptyDir: {}
        {{- end }}
        {{- if .Values.daemonset.useConfigMap }}
        - name: {{ template "datadog.fullname" . }}-datadog-yaml
          configMap:
            name: {{ template "datadog.fullname" . }}-datadog-yaml
        {{- end }}
{{- if .Values.daemonset.volumes }}
{{ toYaml .Values.daemonset.volumes | indent 8 }}
{{- end }}
      {{- if .Values.daemonset.tolerations }}
      tolerations:
{{ toYaml .Values.daemonset.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.daemonset.affinity }}
      affinity:
{{ toYaml .Values.daemonset.affinity | indent 8 }}
      {{- end }}
      serviceAccountName: {{ if .Values.daemonset.rbac.create }}{{ template "datadog.fullname" . }}{{ else }}"{{ .Values.daemonset.rbac.serviceAccountName }}"{{ end }}
      {{- if .Values.daemonset.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.daemonset.nodeSelector | indent 8 }}
      {{- end }}
  updateStrategy:
{{ toYaml .Values.daemonset.updateStrategy | indent 4 }}
{{ end }}
{{ end }}
