# Configuration for testing kube-state-metrics parameters overwrite
kube-state-metrics:
  serviceAccount:
    name: "foo"
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 10m
      memory: 50Mi
